### ISSUE TITLE
set context based on input mode

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3-cli#35] opened 2020-03-11 11:28 UTC
When I use the mock input source in query or create commands the the context.py script fails with the error that root.json could not be found 

```
codeontap@98da86bf35a4:~/cmdb$ cot query list-tiers -i mock
Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/3.6.8/bin/cot", line 8, in <module>
    sys.exit(command.root())
  File "/usr/local/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/cot/backend/common/exceptions.py", line 23, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/cot/command/query/__init__.py", line 84, in list_tiers
    result = query_backend.run(**kwargs, list_tiers=True, cwd=os.getcwd(), _is_cli=True)
  File "/usr/local/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/cot/backend/query/__init__.py", line 42, in run
    ctx = context.Context(cwd)
  File "/usr/local/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/cot/backend/common/context.py", line 94, in __init__
    self.__try_to_find_root()
  File "/usr/local/opt/pyenv/versions/3.6.8/lib/python3.6/site-packages/cot/backend/common/context.py", line 106, in __try_to_find_root
    raise NoRootFileError(f"Can't find {RootLevel.level_file} file.")
cot.backend.common.context.NoRootFileError: Can't find root.json file.
``` 
Using the mock input mode ( -i or --generation-input-source ) a  CMDB is not required and all inputs are managed inside of the engine. 

When using the mock input mode setting the context should be skipped

**Comment by Neketek** [comment] 2020-03-11 12:53
@roleyfoley It's not a bug, It's a feature actually.  Because in order to make everything work your command should look like this ```cot query -i mock list tiers```. Logic is pretty simple here. If subcommands share the same options as parent command or group these options must be provided to the respective parent.  

**For example**

```bash
cot query -i mock describe occurrence -t tier -c component -v version -i instance get [].Core.Version.Id"
```
```bash
cot query <blueprint_generation_options...> describe occurrence <occurrence_query_options...> get <describe_occurrence_subquery_text>
```

**Comment by roleyfoley** [comment] 2020-03-11 13:44
it’s more that when I run this command when I’m not in a cmdb directory. Somewhere there isn’t a root.json  it throws an error. The reason we have the mock input is so you don’t have to have a cmdb folder structure to run mock templates

**Comment by Neketek** [comment] 2020-03-11 13:54
@roleyfoley Ok, but it's an old unfixed version you're using. So, you need a new version, I just tested it again, works as expected. But there is a bug here on the other hand. Wrong exception handling. Need to check why command prints errors in raw python format.

**Comment by Neketek** [comment] 2020-03-11 17:01
Closing this issue because the problem related to the older version.

**Closed by Neketek** 2020-03-11 17:01 UTC
Labels: bug

**Comment by roleyfoley** [comment] 2020-03-12 01:33
Thanks @Neketek I thought I'd tested it on the new cli version, but I must have missed something. Tested on the latest docker image which has the new CLI and all ok
